name: Upload Python Package

#on:
  #release:
    #types: [created]
    
on:
  pull_request:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master          # triggers on pushes that contain changes in master

    
jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest , windows-latest, ubuntu-18.04
        python: [3.6, 3.7]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy cython mdtraj
        pip install  cffi setuptools wheel twine auditwheel
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        echo 'separator'
        auditwheel repair dist/*.whl
        twine upload dist/* --verbose
