name: Upload Python Package

on:
  pull_request:
  push:
    branches:         # array of glob patterns matching against refs/heads. Optional; defaults to all
      - master          # triggers on pushes that contain changes in master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup conda
      uses: s-weigand/setup-conda@master
      with:
        #update-conda: true
        python-version: 3.6
        #conda-channels: anaconda, conda-forge
    - name: publish-to-conda
      uses: Longbowman/conda-package-publish-action@0.3.2
      with:
        subDir: '.'
        AnacondaUsername: ${{ secrets.CONDA_USERNAME }}
        AnacondaPassword: ${{ secrets.CONDA_PASSWORD }}
   
 
   
